Adds uui-box examples
umbraco/UI-Examples pull request #46
Opened 2024-10-10 21:02 UTC by krebil

I've tried my hand at implementing https://github.com/umbraco/UI-Examples/issues/32

As umb-box is not a thing anymore I've added examples for uui-box instead. I'm not sure if there is enough descriptive text or not. 

Let me know about any adjustments you would like me to make.

fixes https://github.com/umbraco/UI-Examples/issues/32

2024-10-12 00:43 UTC, Rockerby requested changes
Hey there @krebil ! Thanks for your contribution to the package 🙌

Great work on this, I think the new page showcases the UUI Box component well. I've added a few comments for you to take a look over before we get this merged in.

2024-10-12 00:43 UTC, Rockerby commented on src/Our.Umbraco.UiExamples.v14/src/scripts/box/box-dashboard.ts
> +                    The uui-box element
Consider updating this with the same text as in the HTML example code ("this is a headline") to make the example directly tie into what the user sees

2024-10-12 00:43 UTC, Rockerby commented on src/Our.Umbraco.UiExamples.v14/src/scripts/box/box-dashboard.ts
> +                    Other header content
Consider updating this with the same text as in the HTML example code ("this is a header") to make the example directly tie into what the user sees

2024-10-12 00:43 UTC, Rockerby commented on src/Our.Umbraco.UiExamples.v14/src/scripts/box/box-dashboard.ts
> +                                The uui-box has largely replaces the umb-box element form previous versions of Umbraco.
Typo; `form` -> `from`

2024-10-12 00:43 UTC, Rockerby commented on src/Our.Umbraco.UiExamples.v14/src/scripts/box/box-dashboard.ts
> +                    </p>
The header slot can also be added via the `header` attribute (like `headline`). Can we add an example of it here too please?

2024-10-12 00:43 UTC, Rockerby commented on src/Our.Umbraco.UiExamples.v14/src/scripts/box/box-dashboard.ts
> +        this is a title
Consider rewording to `this is a headline`

2024-10-12 06:25 UTC, krebil commented on src/Our.Umbraco.UiExamples.v14/src/scripts/box/box-dashboard.ts
> +                    </p>
Actually the only properties on uui-box is headline and headline variant, at least according to the storybook https://uui.umbraco.com/?path=/docs/uui-box--docs

2024-10-12 06:30 UTC, krebil commented
@Rockerby I've updated the text and corrected typos based on your comments. I haven't been able to find any documentation on uui-box with a header property and I can't get it to work when i try myself either. So I haven't added an example for that just yet.

2024-10-13 14:14 UTC, Rockerby commented on src/Our.Umbraco.UiExamples.v14/src/scripts/box/box-dashboard.ts
> +                    </p>
Very correct! Apologies, I was convinced that was an attribute tag as well 😊

2024-10-13 14:17 UTC, merged

2024-10-13 14:19 UTC, Rockerby commented
Thanks @krebil . That looks spot on, changes checked and merged #h5yr!